### ISSUE TITLE
I want to store a policy in DB each time.

### ISSUE THREAD

**Issue by sadayuki-matsuno** [casbin/xorm-adapter#2]
In the current implementation, I think that the table is deleted every time when saving the policy information in the DB.

Then, errors will occur when we save policies at the same time. I want to make CRUD on a line by line basis, make the range of competition as narrow as possible and make it possible to roll back.

That is, I want to insert or delete policy information every time when adding policy information.
Do you plan to prepare such interfaces with casbin?

**Comment by hsluoyz** [comment]
Hi @sadayuki-matsuno ,

This is also one thing that I got in my mind. I think we can add functions like ``AddPolicy()`` and ``RemovePolicy()`` to the adapter interface. But one issue is that there are still adapters that can't operate on line level. For example:

- the protobuf adapter regards all policy rules as a string.
- The same with KV store adapters, all policy rules are stored in one key.

So these adapters can't gain from the two calls, because they still need to save-all and load-all. If I add these two calls to the adapter interface, all other adapters have to support them too. One way to solve is using an empty implementation. So I think it's still doable.

What do you think about this way?

**Comment by sadayuki-matsuno** [comment]
I understood. This is so complicated.
Using an empty implementation is good for me,
because KV stores also have more options to process one line at a time.

**Comment by hsluoyz** [comment]
Hi @sadayuki-matsuno ,

I have added two functions in adapter: ``AddPolicy()`` and ``RemovePolicy()``. An adapter should implement these two functions to provide the auto-save functionality (aka save the policy line by line).

Please see: https://github.com/casbin/casbin/blob/master/persist/adapter.go#L44-L45

Can you help me implement these two functions for Xorm adapter?

**Comment by sadayuki-matsuno** [comment]
Thank you so much!
