### ISSUE TITLE
UpdateFilteredPolicies returns the oldPolicy containing ptype, Is this a bug?

### ISSUE THREAD

**Issue by kkbblzq** [casbin/xorm-adapter#49]
https://github.com/casbin/xorm-adapter/blob/eadfe045b52f90eb635d0a097dafdb2ef53e75ed/adapter.go#L552 
https://github.com/casbin/xorm-adapter/blob/eadfe045b52f90eb635d0a097dafdb2ef53e75ed/adapter.go#L560-L562

will returns the oldPolicy containing ptype

but in usage:
https://github.com/casbin/casbin/blob/c4cf679dfe87889c4228be7172a346282c2efdd4/internal_api.go#L339
https://github.com/casbin/casbin/blob/c4cf679dfe87889c4228be7172a346282c2efdd4/model/policy.go#L271

`model[sec][ptype].PolicyMap` key does not contain ptype
so, it cannot delete policy correctly

I'm not sure if this is an adapter bug or a casbin bug

**Comment by hsluoyz** [comment]
@tangyang9464

**Comment by tangyang9464** [comment]
@kkbblzq I think UpdateFilteredPolicies shouldn't return oldpolicy containing ptype. But almost all adapter implementations follow ``xorm-adapter``. So it seems easier to modify ``casbin`` to be compatible.

**Comment by huijiezheng** [comment]
[](https://github.com/casbin/casbin/blob/9b434269935411da709f6c85a6b59e9ce2401e4c/internal_api.go#L339)
There will panic when the length of oldRules and newRules is not equal, is it better to constraint Adapter return the same format oldRules? I think 337 ~342 code should be remove because the newRules may be empty, or when newRules is empty should return  error? @tangyang9464

**Comment by tangyang9464** [comment]
@JalinWang

**Comment by JalinWang** [comment]
@huijiezheng Thanks. I think you are right and proposed a PR.
